name: Secure Download of .env File

on: [workflow_dispatch]

jobs:
  download-env:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file
        run: |
          echo "SECRET_1=${{ secrets.SECRET_1 }}" >> .env
          echo "SECRET_2=${{ secrets.SECRET_2 }}" >> .env
          echo "SECRET_3=${{ secrets.SECRET_3 }}" >> .env
      - name: Upload .env file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: .env
