name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Start the application in the background
        run: npm start &
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} 
      - name: Run integration tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} 
