name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }} 
      MONGO_KEY: ${{ secrets.MONGO_KEY }} 
      BASE_URL_LOCAL: ${{secrets.BASE_URL_LOCAL}}
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Start the application in the background
        run: npm start &

      - name: Wait for server to be ready
        run: |
          url=${{ secrets.BASE_URL_LOCAL }}
          timeout=30  # Maximum number of seconds to wait
          while ! curl --output /dev/null --silent --fail $url; do
            sleep 1
            timeout=$((timeout-1))
            if [ "$timeout" -le 0 ]; then
              echo "Server did not become ready in time."
              exit 1
            fi
          done
      
      - name: Run integration tests
        run: npm test