name: Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Start the application in the background
        run: npm start &
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
      
      - name: Wait for the server to be ready
        run: |
          echo "Waiting for server to be ready..."
          until $(curl --output /dev/null --silent --fail http://localhost:8080); do
            printf '.'
            sleep 5
          done
      
      - name: Run integration tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} 
          BASE_URL: http://localhost:8080